services:
  marzban-node:
    build: .
    restart: always
    network_mode: host
    env_file: .env

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node

  haproxy:
    image: haproxy:latest
    restart: always
    network_mode: host
    volumes:
      - ./haproxy-XXX-prod.cfg:/usr/local/etc/haproxy/haproxy.cfg

